index
TarasBohun/Lesson1-1 pull request #2
Opened 2022-03-25 14:20 UTC by TarasBohun

2022-03-30 19:35 UTC, ipovos requested changes
Будь ласка, вирішіть merge conflict.

2022-03-30 19:48 UTC, ipovos commented on index2.html
> +    <p>        <s>Перекреслений текст</s></p>
Те, як браузер форматує текст тегів — другорядне. Головне — те, що ті теги позначають:

- [`strong` — важливий, серйозний, або терміновий текст](https://html.spec.whatwg.org/dev/text-level-semantics.html#the-strong-element)
- [`em` — текст, що потребує наголосу](https://html.spec.whatwg.org/dev/text-level-semantics.html#the-em-element)
- [`u` — текст, що не потребує зміни інтонації, але явно позначає примітку вне контексту, наприклад неправильно написане слово](https://html.spec.whatwg.org/dev/text-level-semantics.html#the-u-element)
- [`s` — текст, що втратив свою правильність або актуальність, наприклад стара ціна на ціннику](https://html.spec.whatwg.org/dev/text-level-semantics.html#the-s-element)

2022-03-31 18:57 UTC, TarasBohun commented
я не знаю як вирішити конфлікт між гілками master і branch2

2022-03-31 19:03 UTC, TarasBohun commented
я спробував змерджити їх і щось не виходить.

2022-03-31 19:07 UTC, merged